name: Pull Request Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build LaTeX sprav
      run: |
        docker pull smakevkin/latex-with-times-new-roman:latest
        docker run --rm -v $(pwd):/app smakevkin/latex-with-times-new-roman

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-document
        path: sprav.pdf